import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Seunghak Lee's Portfolio",
  description: "Generated by Seunghak Lee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <div className="container mx-auto">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
